# Generated by Django 6.0.2 on 2026-03-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0003_about_certificate_education_experience_resume_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='focus_areas',
            field=models.TextField(blank=True, help_text='Comma-separated focus areas (e.g. AI System Development, Financial AI)'),
        ),
        migrations.AddField(
            model_name='about',
            name='skills_tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags (e.g. AI, Python, C++)'),
        ),
    ]
