# Generated by Django 6.0.2 on 2026-03-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0004_about_focus_areas_about_skills_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.TextField(blank=True, help_text='Comma-separated features (e.g. Smart Integration, Cloud Setup)'),
        ),
    ]
