# Generated by Django 6.0.2 on 2026-03-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
